<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Randevoo.Application\Randevoo.Application.csproj" />
    <ProjectReference Include="..\Randevoo.Domain\Randevoo.Domain.csproj" />
    <ProjectReference Include="..\Randevoo.Infrastructure\Randevoo.Infrastructure.csproj" />
  </ItemGroup>

</Project>
