using Randevoo.Domain.Enums;

namespace Randevoo.Application.Features.DatingEvents.Common;

public record DatingEventInput(
    string Title,
    string Country,
    string City,
    string? Region,
    decimal Latitude,
    decimal Longitude,
    string Address,
    DateTime DateTimeStart,
    DateTime DateTimeEnd,
    long EventTypeId,
    int MaleMinAge,
    int MaleMaxAge,
    int FemaleMinAge,
    int FemaleMaxAge,
    int MaleCapacity,
    int FemaleCapacity,
    int NumberOfLikesAllowed,
    decimal MaleTicketPrice,
    decimal FemaleTicketPrice,
    EventEducationLevelRestriction EducationLevelRestriction,
    IReadOnlyList<string>? Tags,
    string? EventImage1,
    string? EventImage2,
    string? EventImage3,
    string EventDescriptionHtml,
    decimal? EventPlannerCommissionPercent = null,
    string MaleTicketCurrencyCode = "IRR",
    string FemaleTicketCurrencyCode = "IRR",
    EventPaymentCollectionMethod PaymentCollectionMethod = EventPaymentCollectionMethod.PlatformGateway,
    string? OrganizerPaymentInstructions = null);
