// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Randevoo.Infrastructure.Data;

#nullable disable

namespace Randevoo.Infrastructure.Data.Migrations
{
    [DbContext(typeof(RandevooDbContext))]
    partial class RandevooDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Randevoo.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("AfterJson")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeJson")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.BalanceAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("BalanceAccounts");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.BalanceTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("BalanceAccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DatingEventId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("ReferenceId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BalanceAccountId");

                    b.HasIndex("UserId");

                    b.ToTable("BalanceTransactions");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId", "Name")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CountryId = 1L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Latitude = 35.689200m,
                            Longitude = 51.389000m,
                            Name = "تهران"
                        },
                        new
                        {
                            Id = 2L,
                            CountryId = 1L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            IsDeleted = false,
                            Latitude = 36.260500m,
                            Longitude = 59.616800m,
                            Name = "مشهد"
                        },
                        new
                        {
                            Id = 3L,
                            CountryId = 1L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            IsDeleted = false,
                            Latitude = 29.591800m,
                            Longitude = 52.583700m,
                            Name = "شیراز"
                        },
                        new
                        {
                            Id = 4L,
                            CountryId = 1L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsActive = true,
                            IsDeleted = false,
                            Latitude = 32.654600m,
                            Longitude = 51.668000m,
                            Name = "اصفهان"
                        },
                        new
                        {
                            Id = 5L,
                            CountryId = 1L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsActive = true,
                            IsDeleted = false,
                            Latitude = 38.096200m,
                            Longitude = 46.273800m,
                            Name = "تبریز"
                        },
                        new
                        {
                            Id = 6L,
                            CountryId = 2L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Latitude = 25.204800m,
                            Longitude = 55.270800m,
                            Name = "دبی"
                        },
                        new
                        {
                            Id = 7L,
                            CountryId = 2L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            IsDeleted = false,
                            Latitude = 24.453900m,
                            Longitude = 54.377300m,
                            Name = "ابوظبی"
                        },
                        new
                        {
                            Id = 8L,
                            CountryId = 3L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Latitude = 41.008200m,
                            Longitude = 28.978400m,
                            Name = "استانبول"
                        },
                        new
                        {
                            Id = 9L,
                            CountryId = 3L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            IsDeleted = false,
                            Latitude = 39.933400m,
                            Longitude = 32.859700m,
                            Name = "آنکارا"
                        });
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "IR",
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "ایران"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "AE",
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "امارات متحده عربی"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "TR",
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "ترکیه"
                        });
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.DatingEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long?>("CityId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EducationLevelRestriction")
                        .HasColumnType("int");

                    b.Property<string>("EventDescriptionHtml")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventImage1")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EventImage2")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EventImage3")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("EventPlannerCommissionPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<long>("EventPlannerUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventTypeId")
                        .HasColumnType("bigint");

                    b.Property<int>("FemaleCapacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpenForSell")
                        .HasColumnType("bit");

                    b.Property<int>("MaleCapacity")
                        .HasColumnType("int");

                    b.Property<long?>("MinimumEducationLevelId")
                        .HasColumnType("bigint");

                    b.Property<int>("NumberOfChatAllowed")
                        .HasColumnType("int");

                    b.Property<decimal>("TicketPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("EventPlannerUserId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("MinimumEducationLevelId");

                    b.ToTable("DatingEvents");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.EducationLevelLookup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("EducationLevels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 0,
                            IsActive = true,
                            IsDeleted = false,
                            Rank = 0,
                            Title = "ثبت نشده"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Rank = 1,
                            Title = "دیپلم"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            IsDeleted = false,
                            Rank = 2,
                            Title = "لیسانس"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            IsDeleted = false,
                            Rank = 3,
                            Title = "فوق لیسانس"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsActive = true,
                            IsDeleted = false,
                            Rank = 4,
                            Title = "دکترای حرفه ای / PHD / پزشک / دندان پزشک"
                        });
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.EventChatBlock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BlockedUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("BlockerUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("EventConversationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BlockedUserId");

                    b.HasIndex("BlockerUserId");

                    b.HasIndex("EventConversationId", "BlockerUserId", "BlockedUserId")
                        .IsUnique();

                    b.ToTable("EventChatBlocks");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.EventChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("EventConversationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("SenderUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventConversationId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("EventChatMessages");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.EventConversation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("DatingEventId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DisabledByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("DisabledReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<long>("ParticipantUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("StarterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantUserId");

                    b.HasIndex("StarterUserId");

                    b.HasIndex("DatingEventId", "StarterUserId", "ParticipantUserId")
                        .IsUnique();

                    b.ToTable("EventConversations");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.EventParticipantSmsRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ApprovedMessage")
                        .HasMaxLength(480)
                        .HasColumnType("nvarchar(480)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("DatingEventId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(480)
                        .HasColumnType("nvarchar(480)");

                    b.Property<DateTime?>("PlannedSendAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("QueuedRecipientsCount")
                        .HasColumnType("int");

                    b.Property<long>("RequestedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ReviewedByAdminUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlannedSendAtUtc");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("ReviewedByAdminUserId");

                    b.HasIndex("DatingEventId", "Status", "CreatedAt");

                    b.ToTable("EventParticipantSmsRequests");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.EventPlannerProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("CancelledEventCount")
                        .HasColumnType("int");

                    b.Property<int>("CompletedEventCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasPendingChanges")
                        .HasColumnType("bit");

                    b.Property<int>("HostedEventCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PendingCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PendingFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PendingPictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PendingResume")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("PendingReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("PendingReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("PendingReviewedByAdminUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PendingSubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PendingTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Resume")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalSurveyCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("EventPlannerProfiles");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.EventSurveyRating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("EventSurveyResponseId")
                        .HasColumnType("bigint");

                    b.Property<int>("Factor")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventSurveyResponseId", "Factor")
                        .IsUnique();

                    b.ToTable("EventSurveyRatings");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.EventSurveyResponse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("DatingEventId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("DatingEventId", "UserId")
                        .IsUnique();

                    b.ToTable("EventSurveyResponses");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.EventTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("DatingEventId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("DatingEventId", "TagId")
                        .IsUnique();

                    b.ToTable("EventTags", (string)null);
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.EventTicket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("DatingEventId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRefunded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RemovalReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RemovedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("DatingEventId", "UserId")
                        .IsUnique();

                    b.ToTable("EventTickets");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.EventType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EventTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Social deduction event",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mafia"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Board game social event",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Board Game"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Poetry and conversation event",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Poem Reading"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Casual cafe meetup",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cafe Meetup"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Outdoor hiking event",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Hiking"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Structured short introductions",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Speed Dating"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Competitive game tournament",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Game Tournament"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Learning-focused social workshop",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Workshop"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Art and creativity event",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Art Night"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Music-focused social event",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Music Night"
                        });
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.GenderLookup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Genders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 0,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "نامشخص"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "آقا"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "خانم"
                        });
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.Interest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.ModerationReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdminReviewNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DatingEventId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long?>("EventConversationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<long>("ReportedUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReporterUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ReviewedByAdminUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DatingEventId");

                    b.HasIndex("EventConversationId");

                    b.HasIndex("ReportedUserId");

                    b.HasIndex("ReporterUserId");

                    b.HasIndex("ReviewedByAdminUserId");

                    b.HasIndex("Status");

                    b.ToTable("ModerationReports");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.PlannerWithdrawalRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ReviewedByAdminUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedByAdminUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("Status", "RequestedAtUtc");

                    b.ToTable("PlannerWithdrawalRequests");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.SmsQueueItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("DatingEventId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("EventParticipantSmsRequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(480)
                        .HasColumnType("nvarchar(480)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("PlannedSendAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("RecipientUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DatingEventId");

                    b.HasIndex("EventParticipantSmsRequestId");

                    b.HasIndex("PlannedSendAtUtc");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("SmsQueueItems");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "شب اجتماعی"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "شام"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "کافه"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "بازی"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "هنر"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "کارگاه"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "موسیقی"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "روف تاپ"
                        });
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("EmailConfirmationTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailConfirmationTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MobileLoginCodeExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MobileLoginCodeHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("MobileLoginCodeRequestCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MobileLoginCodeRequestWindowStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MobileLoginFailedAttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MobileLoginLockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PendingEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("MobileNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.UserProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BirthMonth")
                        .HasColumnType("int");

                    b.Property<long?>("CityId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EducationLevel")
                        .HasColumnType("int");

                    b.Property<long?>("EducationLevelId")
                        .HasColumnType("bigint");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<long?>("GenderId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Smoking")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ZodiacSign")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.HasIndex("EducationLevelId");

                    b.HasIndex("GenderId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.UserProfileImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserProfileId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("UserProfileImages");
                });

            modelBuilder.Entity("UserProfileInterest", b =>
                {
                    b.Property<long>("UserProfileId")
                        .HasColumnType("bigint");

                    b.Property<long>("InterestId")
                        .HasColumnType("bigint");

                    b.HasKey("UserProfileId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("UserProfileInterests", (string)null);
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.BalanceAccount", b =>
                {
                    b.HasOne("Randevoo.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("Randevoo.Domain.Entities.BalanceAccount", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.BalanceTransaction", b =>
                {
                    b.HasOne("Randevoo.Domain.Entities.BalanceAccount", "BalanceAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("BalanceAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BalanceAccount");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.City", b =>
                {
                    b.HasOne("Randevoo.Domain.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.DatingEvent", b =>
                {
                    b.HasOne("Randevoo.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Randevoo.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Randevoo.Domain.Entities.User", "EventPlannerUser")
                        .WithMany()
                        .HasForeignKey("EventPlannerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Randevoo.Domain.Entities.EventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Randevoo.Domain.Entities.EducationLevelLookup", "MinimumEducationLevel")
                        .WithMany()
                        .HasForeignKey("MinimumEducationLevelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Randevoo.Domain.ValueObjects.AgeRange", "AgeRangeForFemale", b1 =>
                        {
                            b1.Property<long>("DatingEventId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Max")
                                .HasColumnType("int")
                                .HasColumnName("FemaleMaxAge");

                            b1.Property<int>("Min")
                                .HasColumnType("int")
                                .HasColumnName("FemaleMinAge");

                            b1.HasKey("DatingEventId");

                            b1.ToTable("DatingEvents");

                            b1.WithOwner()
                                .HasForeignKey("DatingEventId");
                        });

                    b.OwnsOne("Randevoo.Domain.ValueObjects.AgeRange", "AgeRangeForMale", b1 =>
                        {
                            b1.Property<long>("DatingEventId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Max")
                                .HasColumnType("int")
                                .HasColumnName("MaleMaxAge");

                            b1.Property<int>("Min")
                                .HasColumnType("int")
                                .HasColumnName("MaleMinAge");

                            b1.HasKey("DatingEventId");

                            b1.ToTable("DatingEvents");

                            b1.WithOwner()
                                .HasForeignKey("DatingEventId");
                        });

                    b.OwnsOne("Randevoo.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<long>("DatingEventId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Region")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Location_Region");

                            b1.HasKey("DatingEventId");

                            b1.ToTable("DatingEvents");

                            b1.WithOwner()
                                .HasForeignKey("DatingEventId");

                            b1.OwnsOne("Randevoo.Domain.ValueObjects.Coordinates", "Coordinates", b2 =>
                                {
                                    b2.Property<long>("LocationDatingEventId")
                                        .HasColumnType("bigint");

                                    b2.Property<decimal>("Latitude")
                                        .HasPrecision(9, 6)
                                        .HasColumnType("decimal(9,6)")
                                        .HasColumnName("Location_Latitude");

                                    b2.Property<decimal>("Longitude")
                                        .HasPrecision(9, 6)
                                        .HasColumnType("decimal(9,6)")
                                        .HasColumnName("Location_Longitude");

                                    b2.HasKey("LocationDatingEventId");

                                    b2.ToTable("DatingEvents");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationDatingEventId");
                                });

                            b1.Navigation("Coordinates")
                                .IsRequired();
                        });

                    b.Navigation("AgeRangeForFemale")
                        .IsRequired();

                    b.Navigation("AgeRangeForMale")
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("EventPlannerUser");

                    b.Navigation("EventType");

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("MinimumEducationLevel");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.EventChatBlock", b =>
                {
                    b.HasOne("Randevoo.Domain.Entities.User", "BlockedUser")
                        .WithMany()
                        .HasForeignKey("BlockedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Randevoo.Domain.Entities.User", "BlockerUser")
                        .WithMany()
                        .HasForeignKey("BlockerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Randevoo.Domain.Entities.EventConversation", "EventConversation")
                        .WithMany("Blocks")
                        .HasForeignKey("EventConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockedUser");

                    b.Navigation("BlockerUser");

                    b.Navigation("EventConversation");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.EventChatMessage", b =>
                {
                    b.HasOne("Randevoo.Domain.Entities.EventConversation", "EventConversation")
                        .WithMany("Messages")
                        .HasForeignKey("EventConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Randevoo.Domain.Entities.User", "SenderUser")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventConversation");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.EventConversation", b =>
                {
                    b.HasOne("Randevoo.Domain.Entities.DatingEvent", "DatingEvent")
                        .WithMany()
                        .HasForeignKey("DatingEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Randevoo.Domain.Entities.User", "ParticipantUser")
                        .WithMany()
                        .HasForeignKey("ParticipantUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Randevoo.Domain.Entities.User", "StarterUser")
                        .WithMany()
                        .HasForeignKey("StarterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatingEvent");

                    b.Navigation("ParticipantUser");

                    b.Navigation("StarterUser");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.EventParticipantSmsRequest", b =>
                {
                    b.HasOne("Randevoo.Domain.Entities.DatingEvent", "DatingEvent")
                        .WithMany()
                        .HasForeignKey("DatingEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Randevoo.Domain.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Randevoo.Domain.Entities.User", "ReviewedByAdminUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DatingEvent");

                    b.Navigation("RequestedByUser");

                    b.Navigation("ReviewedByAdminUser");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.EventPlannerProfile", b =>
                {
                    b.HasOne("Randevoo.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("Randevoo.Domain.Entities.EventPlannerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.EventSurveyRating", b =>
                {
                    b.HasOne("Randevoo.Domain.Entities.EventSurveyResponse", "EventSurveyResponse")
                        .WithMany("Ratings")
                        .HasForeignKey("EventSurveyResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventSurveyResponse");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.EventSurveyResponse", b =>
                {
                    b.HasOne("Randevoo.Domain.Entities.DatingEvent", "DatingEvent")
                        .WithMany()
                        .HasForeignKey("DatingEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Randevoo.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatingEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.EventTag", b =>
                {
                    b.HasOne("Randevoo.Domain.Entities.DatingEvent", "DatingEvent")
                        .WithMany("EventTags")
                        .HasForeignKey("DatingEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Randevoo.Domain.Entities.Tag", "Tag")
                        .WithMany("EventTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatingEvent");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.EventTicket", b =>
                {
                    b.HasOne("Randevoo.Domain.Entities.DatingEvent", "DatingEvent")
                        .WithMany("Tickets")
                        .HasForeignKey("DatingEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Randevoo.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatingEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.ModerationReport", b =>
                {
                    b.HasOne("Randevoo.Domain.Entities.DatingEvent", "DatingEvent")
                        .WithMany()
                        .HasForeignKey("DatingEventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Randevoo.Domain.Entities.EventConversation", "EventConversation")
                        .WithMany()
                        .HasForeignKey("EventConversationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Randevoo.Domain.Entities.User", "ReportedUser")
                        .WithMany()
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Randevoo.Domain.Entities.User", "ReporterUser")
                        .WithMany()
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Randevoo.Domain.Entities.User", "ReviewedByAdminUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DatingEvent");

                    b.Navigation("EventConversation");

                    b.Navigation("ReportedUser");

                    b.Navigation("ReporterUser");

                    b.Navigation("ReviewedByAdminUser");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.PlannerWithdrawalRequest", b =>
                {
                    b.HasOne("Randevoo.Domain.Entities.User", "ReviewedByAdminUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Randevoo.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReviewedByAdminUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Randevoo.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.SmsQueueItem", b =>
                {
                    b.HasOne("Randevoo.Domain.Entities.DatingEvent", "DatingEvent")
                        .WithMany()
                        .HasForeignKey("DatingEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Randevoo.Domain.Entities.EventParticipantSmsRequest", "EventParticipantSmsRequest")
                        .WithMany()
                        .HasForeignKey("EventParticipantSmsRequestId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Randevoo.Domain.Entities.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatingEvent");

                    b.Navigation("EventParticipantSmsRequest");

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("Randevoo.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Randevoo.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Randevoo.Domain.Entities.EducationLevelLookup", "EducationLevelLookup")
                        .WithMany()
                        .HasForeignKey("EducationLevelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Randevoo.Domain.Entities.GenderLookup", "GenderLookup")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Randevoo.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Randevoo.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Randevoo.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<long>("UserProfileId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Region")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Location_Region");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("UserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");

                            b1.OwnsOne("Randevoo.Domain.ValueObjects.Coordinates", "Coordinates", b2 =>
                                {
                                    b2.Property<long>("LocationUserProfileId")
                                        .HasColumnType("bigint");

                                    b2.Property<decimal>("Latitude")
                                        .HasPrecision(9, 6)
                                        .HasColumnType("decimal(9,6)")
                                        .HasColumnName("Location_Latitude");

                                    b2.Property<decimal>("Longitude")
                                        .HasPrecision(9, 6)
                                        .HasColumnType("decimal(9,6)")
                                        .HasColumnName("Location_Longitude");

                                    b2.HasKey("LocationUserProfileId");

                                    b2.ToTable("UserProfiles");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationUserProfileId");
                                });

                            b1.Navigation("Coordinates")
                                .IsRequired();
                        });

                    b.OwnsOne("Randevoo.Domain.ValueObjects.Height", "Height", b1 =>
                        {
                            b1.Property<long>("UserProfileId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Centimeters")
                                .HasColumnType("int")
                                .HasColumnName("HeightCentimeters");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("UserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("EducationLevelLookup");

                    b.Navigation("GenderLookup");

                    b.Navigation("Height")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.UserProfileImage", b =>
                {
                    b.HasOne("Randevoo.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("Images")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("UserProfileInterest", b =>
                {
                    b.HasOne("Randevoo.Domain.Entities.Interest", null)
                        .WithMany()
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Randevoo.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.BalanceAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.DatingEvent", b =>
                {
                    b.Navigation("EventTags");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.EventConversation", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.EventSurveyResponse", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.Tag", b =>
                {
                    b.Navigation("EventTags");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.User", b =>
                {
                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Randevoo.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
