using Randevoo.ControlCenter.Models.Common;

namespace Randevoo.ControlCenter.Services.State;

public sealed class LanguageState
{
    private static AppLanguage s_currentLanguage = AppLanguage.English;

    public event Action? Changed;

    public AppLanguage Current { get; private set; } = s_currentLanguage;

    public bool IsRtl => Current == AppLanguage.Farsi;

    public string Direction => IsRtl ? "rtl" : "ltr";

    public string LanguageCode => IsRtl ? "fa" : "en";

    public void SetLanguage(AppLanguage language)
    {
        s_currentLanguage = language;
        Current = language;
        Changed?.Invoke();
    }

    public string T(string key)
    {
        return Current == AppLanguage.Farsi
            ? Farsi.TryGetValue(key, out var fa) ? fa : key
            : English.TryGetValue(key, out var en) ? en : key;
    }

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["Brand"] = "Randevoo",
        ["ControlCenter"] = "Control Center",
        ["Dashboard"] = "Dashboard",
        ["MyDashboard"] = "My dashboard",
        ["Events"] = "Events",
        ["MyEvents"] = "My events",
        ["EventPlanners"] = "Event planners",
        ["Participants"] = "Participants",
        ["Balances"] = "Balances",
        ["Moderation"] = "Moderation",
        ["Surveys"] = "Surveys",
        ["Chat"] = "Chat",
        ["Settings"] = "Settings",
        ["SignOut"] = "Sign out",
        ["English"] = "EN",
        ["Farsi"] = "FA",
        ["AdminOperations"] = "Admin operations",
        ["PlannerWorkspace"] = "EventPlanner workspace",
        ["EventsDescription"] = "Review events created by planners and confirm them for publication.",
        ["MyEventsDescription"] = "Create and manage events before admin confirmation.",
        ["CreateEvent"] = "Create event",
        ["EventProfile"] = "Event profile",
        ["Event"] = "Event",
        ["Planner"] = "Planner",
        ["Starts"] = "Starts",
        ["Status"] = "Status",
        ["Tickets"] = "Tickets",
        ["Sales"] = "Sales",
        ["Actions"] = "Actions",
        ["Open"] = "Open",
        ["Confirm"] = "Confirm",
        ["PendingAdminReview"] = "Pending admin review",
        ["OnSale"] = "On sale",
        ["Scheduled"] = "Scheduled",
        ["Draft"] = "Draft",
        ["Closed"] = "Closed",
        ["Cancelled"] = "Cancelled",
        ["Venue"] = "Venue",
        ["Country"] = "Country",
        ["Address"] = "Address",
        ["City"] = "City",
        ["Region"] = "Region",
        ["Latitude"] = "Latitude",
        ["Longitude"] = "Longitude",
        ["Capacity"] = "Capacity",
        ["MaleCapacity"] = "Male capacity",
        ["FemaleCapacity"] = "Female capacity",
        ["NumberOfChatAllowed"] = "Chats allowed",
        ["Commission"] = "Planner commission",
        ["TicketsSold"] = "Tickets sold",
        ["TicketPrice"] = "Ticket price",
        ["Audience"] = "Audience",
        ["AgeRangeForMale"] = "Male age range",
        ["AgeRangeForFemale"] = "Female age range",
        ["EventType"] = "Event type",
        ["IsOpenForSell"] = "Open for sell",
        ["Images"] = "Images",
        ["UploadImages"] = "Upload images",
        ["Image1"] = "Image 1",
        ["Image2"] = "Image 2",
        ["Image3"] = "Image 3",
        ["ImagePreview"] = "Image preview",
        ["MapPicker"] = "Map picker",
        ["SelectOnMap"] = "Select location on map",
        ["SelectedLocation"] = "Selected location",
        ["StartDate"] = "Start date",
        ["EndDate"] = "End date",
        ["Description"] = "Description",
        ["RichTextPreview"] = "Preview",
        ["Bold"] = "Bold",
        ["Italic"] = "Italic",
        ["BulletList"] = "Bullet list",
        ["ClearFormat"] = "Clear format",
        ["DomainActions"] = "Event actions",
        ["OpenForSell"] = "Open for sell",
        ["CloseForSell"] = "Close for sell",
        ["CancelEvent"] = "Cancel event",
        ["SetCommission"] = "Set commission",
        ["UpdateEvent"] = "Update event",
        ["UpdateRequiresApproval"] = "Planner updates require admin approval before the event is visible to end users.",
        ["EventUpdated"] = "Event updated and sent for admin review.",
        ["EventActionDone"] = "Event action applied.",
        ["CreatedAt"] = "Created at",
        ["ConfirmedAt"] = "Confirmed at",
        ["NotConfirmed"] = "Not confirmed yet",
        ["BackToEvents"] = "Back to events",
        ["Title"] = "Title",
        ["SaveDraft"] = "Submit for admin review",
        ["NewEventTitle"] = "New event title",
        ["EventCreated"] = "Event submitted for admin review.",
        ["EventConfirmed"] = "Event confirmed by admin.",
        ["NoEvents"] = "No events",
        ["MockPlan"] = "Mock workflow: planner creates an event, admin confirms it, then the event profile shows all details."
    };

    private static readonly IReadOnlyDictionary<string, string> Farsi = new Dictionary<string, string>
    {
        ["Brand"] = "راندوو",
        ["ControlCenter"] = "مرکز کنترل",
        ["Dashboard"] = "داشبورد",
        ["MyDashboard"] = "داشبورد من",
        ["Events"] = "رویدادها",
        ["MyEvents"] = "رویدادهای من",
        ["EventPlanners"] = "برگزارکنندگان",
        ["Participants"] = "شرکت‌کنندگان",
        ["Balances"] = "مالی",
        ["Moderation"] = "نظارت",
        ["Surveys"] = "نظرسنجی‌ها",
        ["Chat"] = "گفتگو",
        ["Settings"] = "تنظیمات",
        ["SignOut"] = "خروج",
        ["English"] = "EN",
        ["Farsi"] = "FA",
        ["AdminOperations"] = "عملیات ادمین",
        ["PlannerWorkspace"] = "فضای برگزارکننده",
        ["EventsDescription"] = "رویدادهای ساخته‌شده توسط برگزارکننده را بررسی و برای انتشار تایید کنید.",
        ["MyEventsDescription"] = "رویداد بسازید و قبل از تایید ادمین مدیریت کنید.",
        ["CreateEvent"] = "ساخت رویداد",
        ["EventProfile"] = "پروفایل رویداد",
        ["Event"] = "رویداد",
        ["Planner"] = "برگزارکننده",
        ["Starts"] = "زمان شروع",
        ["Status"] = "وضعیت",
        ["Tickets"] = "بلیت‌ها",
        ["Sales"] = "فروش",
        ["Actions"] = "عملیات",
        ["Open"] = "مشاهده",
        ["Confirm"] = "تایید",
        ["PendingAdminReview"] = "در انتظار تایید ادمین",
        ["OnSale"] = "در حال فروش",
        ["Scheduled"] = "زمان‌بندی شده",
        ["Draft"] = "پیش‌نویس",
        ["Closed"] = "بسته شده",
        ["Cancelled"] = "لغو شده",
        ["Venue"] = "محل برگزاری",
        ["Country"] = "کشور",
        ["Address"] = "آدرس",
        ["City"] = "شهر",
        ["Region"] = "منطقه",
        ["Latitude"] = "عرض جغرافیایی",
        ["Longitude"] = "طول جغرافیایی",
        ["Capacity"] = "ظرفیت",
        ["MaleCapacity"] = "ظرفیت آقایان",
        ["FemaleCapacity"] = "ظرفیت بانوان",
        ["NumberOfChatAllowed"] = "تعداد گفتگوی مجاز",
        ["Commission"] = "کمیسیون برگزارکننده",
        ["TicketsSold"] = "بلیت فروخته‌شده",
        ["TicketPrice"] = "قیمت بلیت",
        ["Audience"] = "مخاطب",
        ["AgeRangeForMale"] = "بازه سنی آقایان",
        ["AgeRangeForFemale"] = "بازه سنی بانوان",
        ["EventType"] = "نوع رویداد",
        ["IsOpenForSell"] = "باز برای فروش",
        ["Images"] = "تصاویر",
        ["UploadImages"] = "بارگذاری تصاویر",
        ["Image1"] = "تصویر اول",
        ["Image2"] = "تصویر دوم",
        ["Image3"] = "تصویر سوم",
        ["ImagePreview"] = "پیش‌نمایش تصویر",
        ["MapPicker"] = "انتخاب روی نقشه",
        ["SelectOnMap"] = "انتخاب موقعیت روی نقشه",
        ["SelectedLocation"] = "موقعیت انتخاب‌شده",
        ["StartDate"] = "تاریخ شروع",
        ["EndDate"] = "تاریخ پایان",
        ["Description"] = "توضیحات",
        ["RichTextPreview"] = "پیش‌نمایش",
        ["Bold"] = "ضخیم",
        ["Italic"] = "مورب",
        ["BulletList"] = "فهرست",
        ["ClearFormat"] = "پاک کردن قالب",
        ["DomainActions"] = "عملیات رویداد",
        ["OpenForSell"] = "باز کردن فروش",
        ["CloseForSell"] = "بستن فروش",
        ["CancelEvent"] = "لغو رویداد",
        ["SetCommission"] = "ثبت کمیسیون",
        ["UpdateEvent"] = "ویرایش رویداد",
        ["UpdateRequiresApproval"] = "هر ویرایش برگزارکننده باید دوباره توسط ادمین تایید شود تا برای کاربران نهایی نمایش داده شود.",
        ["EventUpdated"] = "رویداد ویرایش شد و برای بررسی ادمین ارسال شد.",
        ["EventActionDone"] = "عملیات رویداد انجام شد.",
        ["CreatedAt"] = "زمان ایجاد",
        ["ConfirmedAt"] = "زمان تایید",
        ["NotConfirmed"] = "هنوز تایید نشده",
        ["BackToEvents"] = "بازگشت به رویدادها",
        ["Title"] = "عنوان",
        ["SaveDraft"] = "ارسال برای بررسی ادمین",
        ["NewEventTitle"] = "عنوان رویداد جدید",
        ["EventCreated"] = "رویداد برای بررسی ادمین ارسال شد.",
        ["EventConfirmed"] = "رویداد توسط ادمین تایید شد.",
        ["NoEvents"] = "رویدادی وجود ندارد",
        ["MockPlan"] = "سناریوی آزمایشی: برگزارکننده رویداد می‌سازد، ادمین تایید می‌کند و پروفایل رویداد همه جزئیات را نشان می‌دهد."
    };
}
